### ISSUE TITLE
JSFiddle link is incorrect

### ISSUE THREAD

**Issue by ascott18** [vuetifyjs/vuetify-issue-helper#42]
Under the repro steps where the different fiddle/pen/sandbox sites are linked, JSFiddle is linked as https://www.jsfiddle.com, but the real site is https://jsfiddle.net/. jsfiddle.com is blocked on my corporate firewall, and doesn't appear to be anything at all (and could be getting used for nefarious purposes)

**Comment by bdeo** [comment]
Closed by ca9448eceb8a14c44df65b41ca20885b3b411cf1. Nice catch, thanks for making an issue about this :)

**Comment by nekosaur** [comment]
Correct commit is 12c44fd55ba5cb0c3bdffe8e28d831efea4b6dda
